{
 "title": "Site Response",
 "description": "Template Site Response, Group: Sites",
 "tags": [ "linux" ],
 "time": { "from": "now-3h", "to": "now-1m" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "Zabbix Data Source",
    "query": "alexanderzobnin-zabbix-datasource"
   },
   { "name": "group", "label": "Group", "query": "/Sites*/" },
   { "name": "host", "label": "Host", "query": "$group.*" },
   { "name": "site", "label": "Site", "query": "$group.$host.Site speed.*" }
  ]
 },
 "panels": [
  { "title": "Site Speed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Page download speed ($site)",
   "type": "graph",
   "description": "The average download speed (bytes per second) that curl measured for the complete download.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Site speed" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Site page download speed/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Site Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Site time ($site)",
   "type": "graph",
   "description": "https://curl.haxx.se/docs/manpage.html",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "Site time" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Site (.*): .*/",
        "$1"
       ],
       "text": "replaceAlias(/Site (.*): .*/, $1)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Site Size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Site time ($site)",
     "type": "graph",
     "description": "https://curl.haxx.se/docs/manpage.html",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "application": { "filter": "Site size" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/Site (.*): .*/",
          "$1"
         ],
         "text": "replaceAlias(/Site (.*): .*/, $1)"
        }
       ],
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/Site .* size/" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "application": { "filter": "CPU" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/CPU (.*) time/",
          "$1"
         ],
         "text": "replaceAlias(/CPU (.*) time/, $1)"
        }
       ],
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "/CPU (interrupt|iowait|nice|softirq|steal|system|user) time$/"
       },
       "options": {
        "showDisabledItems": true
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "PHP-FPM active & idle processes",
     "type": "graph",
     "description": "Number of active & idle PHP-FPM processes",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "PHP-FPM Processes" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "/PHP-FPM (active|idle) processes/"
       },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "CPU time by process (TOP 10)",
     "type": "graph",
     "description": "User & System CPU time for each processes in TOP 5",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "application": { "filter": "CPU" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/CPU (.*) time by process: (.*)/",
          "$2 ($1)"
         ],
         "text": "replaceAlias(/CPU (.*) time by process: (.*)/, $2 ($1))"
        },
        {
         "added": false,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "10",
          "avg"
         ],
         "text": "top(10, avg)"
        }
       ],
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/CPU .* time by process: .*/" },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "application": { "filter": "Memory" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/Memory (.*)/",
          "$1"
         ],
         "text": "replaceAlias(/Memory (.*)/, $1)"
        }
       ],
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/Memory .*/" },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read & Write operations  — total",
     "type": "graph",
     "description": "Суммарная производительность блочных устройств и партиций (кол-во операций в секунду).",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "application": { "filter": "Performance" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "Block devices: read operations total"
       },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Performance" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "Block devices: write operations total"
       },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Read & Write bytes — total",
     "type": "graph",
     "description": "Суммарная производительность блочных устройств и партиций (байт в секунду).",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "application": { "filter": "Performance" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "Block devices: read bytes total"
       },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Performance" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "Block devices: write bytes total"
       },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  { "title": "Network & Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Network traffic on interface",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "Bps", "label": "<-- Out | In -->" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/(Incoming|Outgoing) network traffic on .*/"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}