{
 "title": "PHP-FPM",
 "description": "Template App PHP-FPM, Hosts Group: PHP",
 "tags": [ "linux" ],
 "time": { "from": "now-3h", "to": "now-1m" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "Zabbix Data Source",
    "query": "alexanderzobnin-zabbix-datasource"
   },
   { "name": "group", "label": "Group", "query": "/PHP*/" },
   { "name": "host", "label": "Host", "query": "$group.*" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PHP-FPM Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "PHP-FPM Info" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "PHP-FPM start since" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PHP-FPM pool name",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "PHP-FPM Info" },
     "host": { "filter": "$host" },
     "item": { "filter": "PHP-FPM pool name" },
     "mode": 2,
     "options": {
      "showDisabledItems": false
     },
     "rawSql": "SET statement_timeout=5000;\n\nSELECT \n  CASE WHEN pg_is_in_recovery()='true' \n    THEN 0 \n    ELSE 1 \n  END;",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Number of processes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Processes" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Number of processes" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Context switches per second",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 1 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Performance" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Context switches per second" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Interrupts per second",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 1 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Performance" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Interrupts per second" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PHP-FPM total processes",
   "type": "singlestat",
   "description": "Number of (idle + active) processes",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "PHP-FPM Processes" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "PHP-FPM total processes" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PHP version",
   "type": "singlestat",
   "description": "Full version of PHP from `php --version`",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "PHP-FPM Info" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "PHP version" },
     "mode": 2,
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PHP-FPM ping",
   "type": "graph",
   "description": "Time in milliseconds spent for PHP-FPM '/ping'",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "application": { "filter": "PHP-FPM Info" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "PHP-FPM ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PHP-FPM accepted connections",
   "type": "singlestat",
   "description": "Number of requests accepted by the pool",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "PHP-FPM Connections" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "PHP-FPM accepted connections" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PHP-FPM max active processes",
   "type": "singlestat",
   "description": "Maximum number of active processes since FPM has started",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "PHP-FPM Processes" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "PHP-FPM max active processes" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PHP-FPM slow requests",
   "type": "singlestat",
   "description": "Number of requests that exceeded your 'request_slowlog_timeout' value",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "PHP-FPM Requests" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "PHP-FPM slow requests" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Listen queue length",
   "type": "singlestat",
   "description": "Size of the socket queue of pending connections",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "PHP-FPM Queue" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "PHP-FPM listen queue length" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Max listen queue",
   "type": "singlestat",
   "description": "Maximum number of requests in the queue of pending connections since FPM has started",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "PHP-FPM Queue" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "PHP-FPM max listen queue" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/CPU (.*) time/",
        "$1"
       ],
       "text": "replaceAlias(/CPU (.*) time/, $1)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/CPU (interrupt|iowait|nice|softirq|steal|system|user) time$/"
     },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PHP-FPM active & idle processes",
   "type": "graph",
   "description": "Number of active & idle PHP-FPM processes",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "PHP-FPM Processes" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/PHP-FPM (active|idle) processes/"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU time by process (TOP 10)",
   "type": "graph",
   "description": "User & System CPU time for each processes in TOP 5",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/CPU (.*) time by process: (.*)/",
        "$2 ($1)"
       ],
       "text": "replaceAlias(/CPU (.*) time by process: (.*)/, $2 ($1))"
      },
      {
       "added": false,
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "10",
        "avg"
       ],
       "text": "top(10, avg)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/CPU .* time by process: .*/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "application": { "filter": "Memory" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Memory (.*)/",
        "$1"
       ],
       "text": "replaceAlias(/Memory (.*)/, $1)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Memory .*/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read & Write operations  — total",
     "type": "graph",
     "description": "Суммарная производительность блочных устройств и партиций (кол-во операций в секунду).",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "application": { "filter": "Performance" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "Block devices: read operations total"
       },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Performance" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "Block devices: write operations total"
       },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Read & Write bytes — total",
     "type": "graph",
     "description": "Суммарная производительность блочных устройств и партиций (байт в секунду).",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 68 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "application": { "filter": "Performance" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "Block devices: read bytes total"
       },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Performance" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "Block devices: write bytes total"
       },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "PHP-FPM listen queue",
     "type": "graph",
     "description": "Number of requests in the queue of pending connections",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "PHP-FPM Queue" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": { "filter": "PHP-FPM listen queue" },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "PHP-FPM listen queue length",
     "type": "graph",
     "description": "Size of the socket queue of pending connections",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "PHP-FPM Queue" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": { "filter": "PHP-FPM listen queue length" },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Network & Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "PHP-FPM accepted connections",
     "type": "graph",
     "description": "Number of requests accepted by the pool",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 70 },
     "repeat": "netif",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "PHP-FPM Connections" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": { "filter": "PHP-FPM accepted connections" },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Network traffic on interface",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 83 },
     "yaxes": [
      { "format": "Bps", "label": "<-- Out | In -->" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "/(Incoming|Outgoing) network traffic on .*/"
       },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  }
 ]
}