{
 "title": "Redis",
 "description": "Template App Redis, Hosts Group: Redis",
 "tags": [ "linux" ],
 "time": { "from": "now-3h", "to": "now-1m" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "Zabbix Data Source",
    "query": "alexanderzobnin-zabbix-datasource"
   },
   { "name": "group", "label": "Group", "query": "/Redis*/" },
   { "name": "host", "label": "Host", "query": "$group.*" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Redis Server" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Redis uptime" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Master / Slave",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Redis Replication" },
     "host": { "filter": "$host" },
     "item": { "filter": "Redis role" },
     "mode": 2,
     "options": {
      "showDisabledItems": false
     },
     "rawSql": "SET statement_timeout=5000;\n\nSELECT \n  CASE WHEN pg_is_in_recovery()='true' \n    THEN 0 \n    ELSE 1 \n  END;",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Slaves connected",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Redis Replication" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Redis slaves connected" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Master replication offset",
   "type": "singlestat",
   "description": "Redis master server's current replication offset",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Redis Replication" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Redis master replication offset"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "RDB last save",
   "type": "singlestat",
   "description": "Time spent from last successful RDB save",
   "gridPos": { "h": 3, "w": 5, "x": 16, "y": 1 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Redis Persistence" },
     "functions": [
      {
       "def": {
        "category": "Transform",
        "defaultParams": [
         100
        ],
        "name": "scale",
        "params": [
         {
          "name": "factor",
          "options": [
           100,
           0.01,
           10,
           -1
          ],
          "type": "float"
         }
        ]
       },
       "params": [ "1000" ],
       "text": "scale(1000)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Redis RDB last save" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Redis Server version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Redis Server" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Redis version" },
     "mode": 2,
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Redis ping",
   "type": "graph",
   "description": "Time in milliseconds spent for Redis 'ping' command: redis-cli PING",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "application": { "filter": "Redis Server" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Redis ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Redis latency",
   "type": "graph",
   "description": "Average time in milliseconds from Redis latency measurement: redis-cli --latency",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "application": { "filter": "Redis Server" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Redis latency" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory fragmentation ratio",
   "type": "singlestat",
   "description": "Hit rate = Total key hits / (Total keys hits + Total key misses)",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Redis Memory" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Redis memory fragmentation ratio"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Keyspace hit rate",
   "type": "singlestat",
   "description": "Hit rate = Total key hits / (Total keys hits + Total key misses)",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Redis Keyspace" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Redis keyspace hit rate" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Redis commands processed (per second)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Redis Commands" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Redis commands processed (per second)"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Redis connections (recieved)",
   "type": "singlestat",
   "description": "Number of connections recieved from clients",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Redis Connections" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Redis connections (recieved)" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Redis connections (rejected)",
   "type": "singlestat",
   "description": "Number of connections rejected from clients",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Redis Connections" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Redis connections (rejected)" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/CPU (.*) time/",
        "$1"
       ],
       "text": "replaceAlias(/CPU (.*) time/, $1)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/CPU (interrupt|iowait|nice|softirq|steal|system|user) time$/"
     },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Redis CPU used",
   "type": "graph",
   "description": "* **system**: System CPU consumed by the Redis server\n* **system background**: System CPU consumed by the background processes\n* **used (user)**: User CPU consumed by the Redis server\n* **used (user background)**: User CPU consumed by the background processes",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "Redis CPU" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Redis CPU used .*/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Redis commands CPU time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Redis Commands" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Redis commands: (.*) \\(.*\\)/",
        "$1"
       ],
       "text": "replaceAlias(/Redis commands: (.*) \\(.*\\)/, $1)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/Redis commands: .* \\(CPU time\\)/"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU time by process",
   "type": "graph",
   "description": "User & System CPU time for each processes in TOP 5",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/CPU (.*) time by process: (.*)/",
        "$2 ($1)"
       ],
       "text": "replaceAlias(/CPU (.*) time by process: (.*)/, $2 ($1))"
      },
      {
       "added": false,
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "10",
        "max"
       ],
       "text": "top(10, max)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/CPU .* time by process: .*/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Redis memory fragmentation ratio",
   "type": "graph",
   "description": "Ratio between used_memory_rss and used_memory",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Redis Memory" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Redis memory fragmentation ratio"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Redis memory used",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "application": { "filter": "Redis Memory" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Redis memory used .*/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "collapsed": true,
   "panels": [
    {
     "title": "Redis client biggest input buffer",
     "type": "singlestat",
     "description": "Redis biggest input buffer among current client connections",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 86 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "application": { "filter": "Redis Clients" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "Redis client biggest input buffer"
       },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Redis client longest output list",
     "type": "singlestat",
     "description": "Redis longest output list among current client connections",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 86 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "application": { "filter": "Redis Clients" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "Redis client longest output list"
       },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Read & Write operations  — total",
     "type": "graph",
     "description": "Суммарная производительность блочных устройств и партиций (кол-во операций в секунду).",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "application": { "filter": "Performance" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "Block devices: read operations total"
       },
       "options": {
        "showDisabledItems": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Performance" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "Block devices: write operations total"
       },
       "options": {
        "showDisabledItems": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Read & Write bytes — total ($host)",
     "type": "graph",
     "description": "Суммарная производительность блочных устройств и партиций (байт в секунду).",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 90 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "application": { "filter": "Performance" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "Block devices: read bytes total"
       },
       "options": {
        "showDisabledItems": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Performance" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "Block devices: write bytes total"
       },
       "options": {
        "showDisabledItems": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Commands",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 },
   "collapsed": true,
   "panels": [
    {
     "title": "Redis commands processed (total)",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 87 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "application": { "filter": "Redis Commands" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "Redis commands processed (total)"
       },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Redis commands processed (per second)",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 87 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "application": { "filter": "Redis Commands" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "Redis commands processed (per second)"
       },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Redis commands calls",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 91 },
     "repeat": "disk",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "Redis Commands" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/Redis commands: (.*) \\(.*\\)/",
          "$1"
         ],
         "text": "replaceAlias(/Redis commands: (.*) \\(.*\\)/, $1)"
        }
       ],
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/Redis commands: .* .calls./" },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Redis commands CPU time per call",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 101 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "Redis Commands" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/Redis commands: (.*) \\(.*\\)/",
          "$1"
         ],
         "text": "replaceAlias(/Redis commands: (.*) \\(.*\\)/, $1)"
        }
       ],
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "/Redis commands: .* \\(CPU time per call\\)/"
       },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Keys & Keyspace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "collapsed": true,
   "panels": [
    {
     "title": "Redis keys",
     "type": "graph",
     "description": "* **expired**: Total number of key expiration events\n* **evicted**: Number of evicted keys due to 'maxmemory' limit",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 88 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "Redis Keys" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/Redis keys .*/" },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Keyspace hit rate",
     "type": "graph",
     "description": "Hit rate = Total key hits / (Total keys hits + Total key misses)",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 99 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "Redis Keyspace" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": { "filter": "Redis keyspace hit rate" },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Redis keyspace",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 107 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "Redis Keyspace" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/Redis keyspace (hits|misses)/" },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 },
   "collapsed": true,
   "panels": [
    {
     "title": "Redis connections (recieved)",
     "type": "singlestat",
     "description": "Number of connections recieved from clients",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 146 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "application": { "filter": "Redis Connections" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": { "filter": "Redis connections (recieved)" },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Redis connections (rejected)",
     "type": "singlestat",
     "description": "Number of connections rejected from clients",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 146 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "application": { "filter": "Redis Connections" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": { "filter": "Redis connections (rejected)" },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Redis network rate (read/write)",
     "type": "graph",
     "description": "Network's read/write rate",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 150 },
     "repeat": "netif",
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "application": { "filter": "Redis Network" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/Redis network rate .*/" },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Network traffic on interface",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 163 },
     "yaxes": [
      { "format": "Bps", "label": "<-- Out | In -->" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "/(Incoming|Outgoing) network traffic on .*/"
       },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  }
 ]
}